// ============================================
// CommerceAI — Shared Constants
// ============================================

/** Audit event types */
export const WorkflowEventType = {
  USER_REQUEST: 'USER_REQUEST',
  AGENT_SELECTED: 'AGENT_SELECTED',
  TOOL_AUTHORIZATION: 'TOOL_AUTHORIZATION',
  TOOL_CALLED: 'TOOL_CALLED',
  TOOL_COMPLETED: 'TOOL_COMPLETED',
  POLICY_CHECK: 'POLICY_CHECK',
  USER_CONFIRMATION: 'USER_CONFIRMATION',
  ORDER_UPDATED: 'ORDER_UPDATED',
  WORKFLOW_COMPLETED: 'WORKFLOW_COMPLETED',
  WORKFLOW_FAILED: 'WORKFLOW_FAILED',
  USER_REGISTER: 'USER_REGISTER',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  AGENT_SESSION_START: 'AGENT_SESSION_START',
  AGENT_SESSION_END: 'AGENT_SESSION_END',
  AGENT_TOOL_CALL: 'AGENT_TOOL_CALL',
  TOOL_VALIDATION_FAILED: 'TOOL_VALIDATION_FAILED',
  UNKNOWN_TOOL_ATTEMPT: 'UNKNOWN_TOOL_ATTEMPT',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  POLICY_VIOLATION: 'POLICY_VIOLATION',
  CART_ITEM_ADDED: 'CART_ITEM_ADDED',
  CART_ITEM_REMOVED: 'CART_ITEM_REMOVED',
  CART_ITEM_UPDATED: 'CART_ITEM_UPDATED',
  ORDER_CREATED: 'ORDER_CREATED',
  PAYMENT_INITIATED: 'PAYMENT_INITIATED',
  PAYMENT_VERIFIED: 'PAYMENT_VERIFIED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  WEBHOOK_RECEIVED: 'WEBHOOK_RECEIVED',
  WEBHOOK_VERIFIED: 'WEBHOOK_VERIFIED',
  WEBHOOK_INVALID_SIGNATURE: 'WEBHOOK_INVALID_SIGNATURE',
  WEBHOOK_PAYMENT_CAPTURED: 'WEBHOOK_PAYMENT_CAPTURED',
  ORDER_COMPLETED: 'ORDER_COMPLETED',
  INTENT_CLASSIFIED: 'INTENT_CLASSIFIED',
  AGENT_RESPONSE_GENERATED: 'AGENT_RESPONSE_GENERATED',
} as const;

export type WorkflowEventType = (typeof WorkflowEventType)[keyof typeof WorkflowEventType];

/** Order status transitions */
export const VALID_ORDER_TRANSITIONS: Record<string, string[]> = {
  CREATED: ['PAYMENT_INITIATED', 'CANCELLED'],
  PAYMENT_INITIATED: ['PAYMENT_PROCESSING', 'PAYMENT_FAILED', 'CANCELLED'],
  PAYMENT_PROCESSING: ['PAYMENT_VERIFIED', 'PAYMENT_FAILED'],
  PAYMENT_VERIFIED: ['PAYMENT_CAPTURED', 'PAYMENT_FAILED'],
  PAYMENT_CAPTURED: ['ORDER_COMPLETE'],
  PAYMENT_FAILED: ['PAYMENT_INITIATED', 'CANCELLED'],
  ORDER_COMPLETE: [],
  CANCELLED: [],
};
