"use strict";
// ============================================
// CommerceAI — Shared Constants
// ============================================
Object.defineProperty(exports, "__esModule", { value: true });
exports.VALID_ORDER_TRANSITIONS = exports.AuditEventTypes = void 0;
/** Audit event types */
exports.AuditEventTypes = {
    USER_REGISTER: 'USER_REGISTER',
    USER_LOGIN: 'USER_LOGIN',
    USER_LOGOUT: 'USER_LOGOUT',
    AGENT_SESSION_START: 'AGENT_SESSION_START',
    AGENT_SESSION_END: 'AGENT_SESSION_END',
    AGENT_TOOL_CALL: 'AGENT_TOOL_CALL',
    TOOL_VALIDATION_FAILED: 'TOOL_VALIDATION_FAILED',
    UNKNOWN_TOOL_ATTEMPT: 'UNKNOWN_TOOL_ATTEMPT',
    PERMISSION_DENIED: 'PERMISSION_DENIED',
    POLICY_VIOLATION: 'POLICY_VIOLATION',
    CART_ITEM_ADDED: 'CART_ITEM_ADDED',
    CART_ITEM_REMOVED: 'CART_ITEM_REMOVED',
    CART_ITEM_UPDATED: 'CART_ITEM_UPDATED',
    ORDER_CREATED: 'ORDER_CREATED',
    PAYMENT_INITIATED: 'PAYMENT_INITIATED',
    PAYMENT_VERIFIED: 'PAYMENT_VERIFIED',
    PAYMENT_FAILED: 'PAYMENT_FAILED',
    WEBHOOK_RECEIVED: 'WEBHOOK_RECEIVED',
    WEBHOOK_VERIFIED: 'WEBHOOK_VERIFIED',
    WEBHOOK_INVALID_SIGNATURE: 'WEBHOOK_INVALID_SIGNATURE',
    WEBHOOK_PAYMENT_CAPTURED: 'WEBHOOK_PAYMENT_CAPTURED',
    ORDER_COMPLETED: 'ORDER_COMPLETED',
    INTENT_CLASSIFIED: 'INTENT_CLASSIFIED',
    AGENT_RESPONSE_GENERATED: 'AGENT_RESPONSE_GENERATED',
};
/** Order status transitions */
exports.VALID_ORDER_TRANSITIONS = {
    CREATED: ['PAYMENT_INITIATED', 'CANCELLED'],
    PAYMENT_INITIATED: ['PAYMENT_PROCESSING', 'PAYMENT_FAILED', 'CANCELLED'],
    PAYMENT_PROCESSING: ['PAYMENT_VERIFIED', 'PAYMENT_FAILED'],
    PAYMENT_VERIFIED: ['PAYMENT_CAPTURED', 'PAYMENT_FAILED'],
    PAYMENT_CAPTURED: ['ORDER_COMPLETE'],
    PAYMENT_FAILED: ['PAYMENT_INITIATED', 'CANCELLED'],
    ORDER_COMPLETE: [],
    CANCELLED: [],
};
//# sourceMappingURL=constants.js.map